In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
df=pd.read_csv(r"C:\Users\DELL\Documents\house.csv")
df

id  area  bedroom  age  price
0   1  2000      3.0   20  55000
1   2  3000      4.0   15  58000
2   3  3200      NaN   17  60000
3   4  3500      3.0   25  50000
4   5  4000      4.0    8  75000

In [2]:
import math
med_bed=math.floor(df.bedroom.median())
med_bed

3

In [3]:
df.bedroom=df.bedroom.fillna(med_bed)
df

id  area  bedroom  age  price
0   1  2000      3.0   20  55000
1   2  3000      4.0   15  58000
2   3  3200      3.0   17  60000
3   4  3500      3.0   25  50000
4   5  4000      4.0    8  75000

In [4]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [5]:
reg.coef_

array([ 2.64427625e+00, -5.44776321e+03, -1.67576700e+03])

In [6]:
reg.intercept_

98307.40640626801

In [7]:
reg.predict([[3000,3,40]])

array([22866.26571158])

In [8]:
reg.predict([[3200,3,17]])

array([61937.76185971])

In [9]:
reg.predict([[2000,3,20]])

array([53737.32936883])